# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "bun"
    open-pull-requests-limit: 0 # limit does not apply for security PRs
    directory: "/"
    schedule:
      interval: daily
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "bun" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      docusaurus-dependencies: # docusaurus and critical updates
        applies-to: version-updates
        patterns:
          - "@docusaurus*"
          - "docusaurus-*"
          - "react*"
          - "@scalar/api-reference-react"

      other-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "@docusaurus*"
          - "docusaurus-*"
          - "react*"
          - "@scalar/api-reference-react"
        update-types:
          - minor
          - patch

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
